datadog:
  apiKeyExistingSecret: "datadog-secret"
  tags:
    - "env:ctf"
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          namespaceSelector:
            matchNames:
              - "default"
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"
  logs:
    enabled: true
    containerCollectAll: true
  asm:
    threats:
      enabled: true
    sca:
      enabled: true
    iast:
      enabled: true
  securityAgent:
    runtime:
      enabled: true
  networkMonitoring:
    enabled: true
