apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: ${NAMESPACE_NAME}
spec:
  global:
    clusterName: ${CLUSTER_NAME}
    credentials:
      apiSecret:
        secretName: ${SECRETS_NAME}
        keyName: "apikey"
  override:
    nodeAgent:
      env:
      - name: DD_CONTAINER_EXCLUDE_LOGS
        value: "namespace:kube-system"
  features:
    admissionController:
      enabled: true
    apm:
      enabled: true
      instrumentation:
        enabled: true
        enabledNamespaces:
          - "default"
          - "base"
        libVersions:
          java: "1"
          dotnet: "3"
          python: "2"
          js: "5"
          ruby: "2"
          php: "1"
    logCollection:
      enabled: true
      containerCollectAll: true
    cws:
      enabled: true
    usm:
      enabled: true
    npm:
      enabled: true